version: '3'
services:
  python:
    build: .
    command: gunicorn -b 0.0.0.0:3000 --reload app:app
    environment:
        - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "3000:3000"
